CREATE TYPE "resolution_status" AS ENUM('pending', 'processing', 'resolved', 'failed');--> statement-breakpoint
ALTER TABLE "nutrient_profile" ADD COLUMN "source_release_id" uuid;--> statement-breakpoint
ALTER TABLE "food_serving" ADD COLUMN "source_release_id" uuid;--> statement-breakpoint
ALTER TABLE "nutrient_profile" ADD CONSTRAINT "nutrient_profile_source_release_id_source_release_id_fk" FOREIGN KEY ("source_release_id") REFERENCES "source_release"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "food_serving" ADD CONSTRAINT "food_serving_source_release_id_source_release_id_fk" FOREIGN KEY ("source_release_id") REFERENCES "source_release"("id") ON DELETE restrict;--> statement-breakpoint
CREATE INDEX "nutrient_profile_source_release_idx" ON "nutrient_profile" ("source_release_id");--> statement-breakpoint
CREATE INDEX "food_serving_source_release_idx" ON "food_serving" ("source_release_id");--> statement-breakpoint
CREATE TYPE "mapping_decision_status" AS ENUM('review_required', 'selected', 'unresolved');--> statement-breakpoint
CREATE TYPE "mapping_decision_method" AS ENUM('exact', 'lexical', 'user_selected', 'manual');--> statement-breakpoint
CREATE TABLE "recognition_attempt" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "meal_log_id" uuid NOT NULL UNIQUE, "image_asset_id" uuid NOT NULL, "status" "recognition_status" DEFAULT 'pending' NOT NULL, "provider" "recognition_provider", "model" text, "prompt_version" text, "schema_version" text, "provider_request_id" text, "input_tokens" integer DEFAULT 0 NOT NULL, "output_tokens" integer DEFAULT 0 NOT NULL, "attempt_count" integer DEFAULT 0 NOT NULL, "lease_token" uuid, "lease_expires_at" timestamp with time zone, "next_attempt_at" timestamp with time zone DEFAULT now() NOT NULL, "last_error_code" text, "completed_at" timestamp with time zone, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "recognition_attempt_counts_check" CHECK ("attempt_count" >= 0 AND "input_tokens" >= 0 AND "output_tokens" >= 0), CONSTRAINT "recognition_attempt_lease_check" CHECK (("status" = 'processing' AND "lease_token" IS NOT NULL AND "lease_expires_at" IS NOT NULL) OR ("status" <> 'processing' AND "lease_token" IS NULL AND "lease_expires_at" IS NULL)));--> statement-breakpoint
CREATE TABLE "stored_observation" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "meal_log_id" uuid NOT NULL UNIQUE, "recognition_attempt_id" uuid NOT NULL UNIQUE, "provider" "recognition_provider" NOT NULL, "model" text NOT NULL, "prompt_version" text NOT NULL, "schema_version" text NOT NULL, "provider_request_id" text, "input_tokens" integer NOT NULL, "output_tokens" integer NOT NULL, "canonical_content" jsonb NOT NULL, "content_sha256" text NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "stored_observation_tokens_check" CHECK ("input_tokens" >= 0 AND "output_tokens" >= 0), CONSTRAINT "stored_observation_content_check" CHECK (jsonb_typeof("canonical_content") = 'object' AND "content_sha256" ~ '^[0-9a-f]{64}$'));--> statement-breakpoint
CREATE TABLE "resolution_attempt" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "stored_observation_id" uuid NOT NULL UNIQUE, "status" "resolution_status" DEFAULT 'pending' NOT NULL, "attempt_count" integer DEFAULT 0 NOT NULL, "lease_token" uuid, "lease_expires_at" timestamp with time zone, "next_attempt_at" timestamp with time zone DEFAULT now() NOT NULL, "last_error_code" text, "resolved_at" timestamp with time zone, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "resolution_attempt_count_check" CHECK ("attempt_count" >= 0), CONSTRAINT "resolution_attempt_lease_check" CHECK (("status" = 'processing' AND "lease_token" IS NOT NULL AND "lease_expires_at" IS NOT NULL) OR ("status" <> 'processing' AND "lease_token" IS NULL AND "lease_expires_at" IS NULL)), CONSTRAINT "resolution_attempt_resolved_check" CHECK ("status" <> 'resolved' OR "resolved_at" IS NOT NULL));--> statement-breakpoint
CREATE TABLE "mapping_decision" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "stored_observation_id" uuid NOT NULL, "local_observation_id" text NOT NULL, "catalog_release_id" uuid NOT NULL, "release_activation_id" uuid NOT NULL, "resolver_version" text NOT NULL, "resolver_sha256" text NOT NULL, "policy_version" text NOT NULL, "policy_sha256" text NOT NULL, "candidates" jsonb NOT NULL, "selected_food_id" uuid, "status" "mapping_decision_status" NOT NULL, "method" "mapping_decision_method" NOT NULL, "reason_code" text NOT NULL, "evidence" jsonb NOT NULL, "predecessor_id" uuid, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "mapping_decision_content_check" CHECK (jsonb_typeof("candidates") = 'array' AND jsonb_array_length("candidates") <= 8 AND jsonb_typeof("evidence") = 'object'), CONSTRAINT "mapping_decision_hash_check" CHECK ("resolver_sha256" ~ '^[0-9a-f]{64}$' AND "policy_sha256" ~ '^[0-9a-f]{64}$'));--> statement-breakpoint
CREATE TABLE "calculation_preview" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "meal_log_id" uuid NOT NULL, "root_mapping_decision_id" uuid NOT NULL, "root_revision" integer NOT NULL, "catalog_release_id" uuid NOT NULL, "release_activation_id" uuid NOT NULL, "discriminant" text NOT NULL, "identity" jsonb NOT NULL, "content_sha256" text NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "calculation_preview_identity_check" CHECK ("root_revision" > 0 AND length(trim("discriminant")) > 0 AND jsonb_typeof("identity") = 'object' AND "content_sha256" ~ '^[0-9a-f]{64}$'));--> statement-breakpoint
ALTER TABLE "recognition_attempt" ADD CONSTRAINT "recognition_attempt_meal_fk" FOREIGN KEY ("meal_log_id") REFERENCES "meal_log"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "recognition_attempt" ADD CONSTRAINT "recognition_attempt_image_fk" FOREIGN KEY ("image_asset_id") REFERENCES "image_asset"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "stored_observation" ADD CONSTRAINT "stored_observation_meal_fk" FOREIGN KEY ("meal_log_id") REFERENCES "meal_log"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "stored_observation" ADD CONSTRAINT "stored_observation_attempt_fk" FOREIGN KEY ("recognition_attempt_id") REFERENCES "recognition_attempt"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "resolution_attempt" ADD CONSTRAINT "resolution_attempt_observation_fk" FOREIGN KEY ("stored_observation_id") REFERENCES "stored_observation"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "mapping_decision" ADD CONSTRAINT "mapping_decision_observation_fk" FOREIGN KEY ("stored_observation_id") REFERENCES "stored_observation"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "mapping_decision" ADD CONSTRAINT "mapping_decision_release_fk" FOREIGN KEY ("catalog_release_id") REFERENCES "catalog_release"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "mapping_decision" ADD CONSTRAINT "mapping_decision_activation_fk" FOREIGN KEY ("release_activation_id") REFERENCES "release_activation"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "mapping_decision" ADD CONSTRAINT "mapping_decision_food_fk" FOREIGN KEY ("selected_food_id") REFERENCES "food"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "mapping_decision" ADD CONSTRAINT "mapping_decision_predecessor_fk" FOREIGN KEY ("predecessor_id") REFERENCES "mapping_decision"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "calculation_preview" ADD CONSTRAINT "calculation_preview_meal_fk" FOREIGN KEY ("meal_log_id") REFERENCES "meal_log"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "calculation_preview" ADD CONSTRAINT "calculation_preview_decision_fk" FOREIGN KEY ("root_mapping_decision_id") REFERENCES "mapping_decision"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "calculation_preview" ADD CONSTRAINT "calculation_preview_release_fk" FOREIGN KEY ("catalog_release_id") REFERENCES "catalog_release"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "calculation_preview" ADD CONSTRAINT "calculation_preview_activation_fk" FOREIGN KEY ("release_activation_id") REFERENCES "release_activation"("id") ON DELETE restrict;--> statement-breakpoint
CREATE INDEX "recognition_attempt_due_idx" ON "recognition_attempt" ("status","next_attempt_at");--> statement-breakpoint
CREATE UNIQUE INDEX "stored_observation_content_unique" ON "stored_observation" ("meal_log_id","content_sha256");--> statement-breakpoint
CREATE INDEX "resolution_attempt_due_idx" ON "resolution_attempt" ("status","next_attempt_at");--> statement-breakpoint
CREATE INDEX "mapping_decision_observation_idx" ON "mapping_decision" ("stored_observation_id","local_observation_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "calculation_preview_identity_unique" ON "calculation_preview" ("meal_log_id","root_mapping_decision_id","root_revision","content_sha256");--> statement-breakpoint
CREATE INDEX "calculation_preview_meal_root_idx" ON "calculation_preview" ("meal_log_id","root_revision");--> statement-breakpoint
CREATE OR REPLACE FUNCTION reject_append_only_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME; END; $$;--> statement-breakpoint
CREATE TRIGGER stored_observation_append_only BEFORE UPDATE OR DELETE ON "stored_observation" FOR EACH ROW WHEN (pg_trigger_depth() = 0) EXECUTE FUNCTION reject_append_only_mutation();--> statement-breakpoint
CREATE TRIGGER mapping_decision_append_only BEFORE UPDATE OR DELETE ON "mapping_decision" FOR EACH ROW WHEN (pg_trigger_depth() = 0) EXECUTE FUNCTION reject_append_only_mutation();--> statement-breakpoint
CREATE TRIGGER calculation_preview_append_only BEFORE UPDATE OR DELETE ON "calculation_preview" FOR EACH ROW WHEN (pg_trigger_depth() = 0) EXECUTE FUNCTION reject_append_only_mutation();
--> statement-breakpoint
ALTER TABLE "meal_log" DROP CONSTRAINT "meal_log_recognition_ready_check";--> statement-breakpoint
ALTER TABLE "meal_log" ADD CONSTRAINT "meal_log_recognition_ready_check" CHECK ("recognition_status" <> 'ready' OR ("recognition_provider" IS NOT NULL AND "recognition_model" IS NOT NULL AND "recognition_prompt_version" IS NOT NULL AND "recognition_schema_version" IS NOT NULL AND "recognition_result" IS NOT NULL AND jsonb_typeof("recognition_result") = 'object' AND (("recognition_result"->>'version' = '2' AND "recognition_result" ? 'foods' AND jsonb_typeof("recognition_result"->'foods') = 'array') OR ("recognition_result"->>'version' = '3' AND "recognition_result" ? 'observations' AND jsonb_typeof("recognition_result"->'observations') = 'array')) AND "recognition_completed_at" IS NOT NULL));
